### ISSUE TITLE
CSS being cached between emails

### ISSUE THREAD

**Issue by veganista** [fedeisas/laravel-mail-css-inliner#114]
`CssInlinerPlugin::$css` is cached between different inlines.

This is probably intended but if you try to send 2 emails that have different templates you can run into issues.

*css/email.css*
```css
h1 {
  color: red;
}
```

*mail/email1.blade.php*

```blade
<html>
    <head>
        <link rel="stylesheet" href="{{ public_path('css/email.css') }}">
    </head>
    <body>
        <h1>Hello</h1>
    </body>
</html>
```

*mail/email2.blade.php*

```blade
<html>
    <body>
        <h1>Hello</h1>
    </body>
</html>
```

If email 1 is sent *before* email 2 they will both be inlined as:

```html
<html>
    <body>
        <h1 style="color:red">Hello</h1>
    </body>
</html>
```

I've checked the value of ```$this->css``` and it is not reset between calls in the same request.

My current solution is to inline the CSS instead of using a link:

```blade
<html>
    <head>
        <style>{{ get_file_contents(public_path('css/email.css')) }}</style>
    </head>
    <body>
        <h1>Hello</h1>
    </body>
</html>
```

**Comment by fedeisas** [comment]
@veganista thanks for your feedback. I did some changes to improve this section of the code. Please try the latest version. Thanks.
