### ISSUE TITLE
Error loading CSS files like //fonts.googleapis.com

### ISSUE THREAD

**Issue by djereg** [fedeisas/laravel-mail-css-inliner#117]
I have one service that forwards some mails according to some rules. That's not really the important thing.

But, today got one mail form google, which contains the next:
```html
<link href="//fonts.googleapis.com/css?family=Google+Sans" rel="stylesheet" type="text/css"/>
```

When the inliner tries to load the file, it fails with error: 
```
file_get_contents(//fonts.googleapis.com/css?family=Google+Sans): failed to open stream: No such file or directory
```

The problem is here:
https://github.com/fedeisas/laravel-mail-css-inliner/blob/b45b3ed65966324f5094b51aa616445725074ce1/src/CssInlinerPlugin.php#L61-L73

I think checking the path that it begins with `//` and prepending `http:` should fix the problem, but for now I would just raise the idea to see if anyone has a better idea for it.

**Comment by tahirpk** [comment]
You can add the google font in your css file, in this way:
@media screen  {
@font-face {
    font-family: 'Kanit';
    font-style: normal;
    font-weight: 400;
    src: local('Kanit'), local('Kanit Regular'), local('Kanit-Regular'), url(https://fonts.googleapis.com/css?family=Kanit:300,400,600,700&subset=latin-ext) format('Kanit');
  }
---body css
}

**Comment by djereg** [comment]
I can, but will not solve my problem.

As I wrote, the service forwards some incoming mails, which come from different sources. So the above will not solve my problem, because the mail what comes from google will contain the `<link />` with the above path, and the inliner will try to load it, and will fail.

https://stackoverflow.com/questions/7273573/links-start-with-two-slashes

**Comment by fedeisas** [comment]
@djereg please try the latest version. Thanks.
