### ISSUE TITLE
Laravel 8 Support pls

### ISSUE THREAD

**Issue by nam-co** [fedeisas/laravel-mail-css-inliner#120]
Hi theres a small problem when upgrading/installing on L8, basically the error is "fedeisas/laravel-mail-css-inliner 3.0 requires illuminate/support ^7.4", can you pls upgrade the package

Appreciate the time you put into this package

**Comment by nam-co** [comment]
Thanks

**Comment by fedeisas** [comment]
@nam-co please try the latest version. Thanks.

**Comment by nam-co** [comment]
Hi @fedeisas it seems to be working now, composer update worked, I have to update other packages to complete 8 upgrade and I will let you know when I can test, thanks
