### ISSUE TITLE
CSS Inliner tries to resolve URL, not path, in some cases

### ISSUE THREAD

**Issue by superbiche** [fedeisas/laravel-mail-css-inliner#130]
Version: 2.3
Laravel: 6.18.15

```php
// config/css-inliner.php
<?php
return [
	'css-files' => [
	    public_path('css/mail.css'),
    ],
];
```
```html
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>

    <link href="{{ asset('css/mail.css') }}" rel="stylesheet">
</head>
<body <!-- ... --> </body>
</html>
```

Error:  
```
  ErrorException  : file_get_contents(): php_network_getaddresses: getaddrinfo failed: Name or service not known

  at /var/www/html/vendor/fedeisas/laravel-mail-css-inliner/src/CssInlinerPlugin.php:70
    66|     {
    67|         if (isset($options['css-files']) && count($options['css-files']) > 0) {
    68|             $this->css = '';
    69|             foreach ($options['css-files'] as $file) {
  > 70|                 $this->css .= file_get_contents($file);
    71|             }
    72|         }
    73|     }
    74| 

  Exception trace:

  1   file_get_contents("http://holyday.docker/css/mail.css")
      /var/www/html/vendor/fedeisas/laravel-mail-css-inliner/src/CssInlinerPlugin.php:70

  2   Fedeisas\LaravelMailCssInliner\CssInlinerPlugin::loadOptions([])
      /var/www/html/vendor/fedeisas/laravel-mail-css-inliner/src/CssInlinerPlugin.php:108

```

Seems the plugin tries to resolve the URL path when I use `asset()`. Which is weird: on my machine, it happens once, then it works, on my colleague's machine, it fails every time.  

I really don't know what happens there.

**Comment by DannyvdSluijs** [comment]
@superbiche In an attempt to cleanup this repository I'm looking at the open issues including yours.
I quickly noticed the issue is close to two years old, Laravel 6 is a almost[ End Of Life](https://laravel.com/docs/6.x/releases) and you're using version 2.3 of this library which dates back to 2019. 

I value your opinion here and was wondering if you think there is any value in looking into this issue or could we close and see when someone opens the same issue?

**Comment by superbiche** [comment]
@DannyvdSluijs I think this can be closed, it's so old I cannot remember exactly what didn't work, as we're using this package in production since then. So yeah feel free to close it!
