### ISSUE TITLE
Does link stylesheet should include file content in head ?

### ISSUE THREAD

**Issue by Mushr0000m** [fedeisas/laravel-mail-css-inliner#139]
From the doc it says that this :
```
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="./tests/css/test.css">
    </head>
    <body>
        <h1>Hey you</h1>
    </body>
</html>
```
will turn into this : 
```
<html>
    <head>
        <style>
            h1 {
                font-size: 24px;
                color: #000;
            }
        </style>
    </head>
    <body>
        <h1 style="font-size: 24px; color: #000;">Hey you</h1>
    </body>
</html>
```

But when I do it like this : 
```
<link rel="stylesheet" type="text/css" href="{{ URL::asset('theme/emails.min.css') }}">
```
The style is well inlined but not pasted in a `<style>` tag in the head, replacing the `<link>` one. Shouldn't it ?

**Comment by fedeisas** [comment]
I think the docs are wrong. Or we changed the behaviour at some point.

Isn't it redundant, though?

**Comment by Mushr0000m** [comment]
I’m not sure what you mean by redundant.
- External stylesheet with link tag are erased by a lot of email client so having it automaticaly embeded is better.  
- Also it can’t be completely removed from the head because of some rules like media queries, hover, etc that can’t be inlined on tags. 

I just think that using link is great because we can use webpack/sass to create the style file, using autoprefixer etc, and it’s easy to include it in the head. So if your package could paste the content to replace the link tag like in the doc we could take the best of both world 😁

**Comment by DannyvdSluijs** [comment]
@Mushr0000m  In an attempt to cleanup this repository I'm looking at the open issues including yours.
It seems you're asking for adding an additional feature if I'm right? 

I value your input here and was wondering if you could verify this is still the case and support for external css hasn't been added in since the opening of your ticket.

**Comment by DannyvdSluijs** [comment]
@Mushr0000m I'll close the issue for now. If you think this is incorrect and at any time want to revisit this issue feel free to open it.
