### ISSUE TITLE
Support for PHP 8

### ISSUE THREAD

**Issue by phanan** [fedeisas/laravel-mail-css-inliner#145]
With PHP 8 released and the main dependency [tijsverkoyen/css-to-inline-styles](https://github.com/tijsverkoyen/CssToInlineStyles/blob/master/composer.json#L15) supporting it since a while ago, can we bump the PHP dependency to `^7 || ^8`?

**Comment by joshuaeasy** [comment]
Please can make the PHP dependency to ^7 || ^8?

**Comment by duxthefux** [comment]
can we get the https://github.com/fedeisas/laravel-mail-css-inliner/pull/146 merged?

**Comment by ajohnson6494** [comment]
@fedeisas Can we get a release with PHP 8 support now the composer updates are merged?

**Comment by fedeisas** [comment]
@ajohnson6494 done with `4.0`
