### ISSUE TITLE
Laravel 5

### ISSUE THREAD

**Issue by freekmurze** [fedeisas/laravel-mail-css-inliner#16]
Could you please update the composer.json so that this package can be used with Laravel 5?

**Comment by renege** [comment]
not working on L5

**Comment by GrahamCampbell** [comment]
@renege Are you using dev stability. The last tag won't work on L4.

**Comment by GrahamCampbell** [comment]
> Could you please update the composer.json so that this package can be used with Laravel 5?

Yeh, it is updated. Look at it...

**Comment by sebdesign** [comment]
It worked for me by using `"fedeisas/laravel-mail-css-inliner": "@dev"`

**Comment by freekmurze** [comment]
Is there already a version tagged that works with Laravel 5?

**Comment by duellsy** [comment]
Looks like it's available for 5.0 now, but hoping this could also be updated to be installable on Laravel 5.1?

**Comment by Jaspur** [comment]
L5.1 not working

**Comment by Mastergalen** [comment]
Works on Laravel 5.1 for me using `"fedeisas/laravel-mail-css-inliner": "@dev"`

**Comment by bandaranaike** [comment]
I've tried with L 5.1. Was error occurred.
`composer require "fedeisas/laravel-mail-css-inliner": "@dev"
                                                                                           
  [InvalidArgumentException]                                                                                                            
  Could not find package @dev at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability  `

**Comment by ceesvanegmond** [comment]
Done: see #26
