### ISSUE TITLE
Updating dependencies Your requirements could not be resolved to an installable set of packages.    Problem 1     - Root composer.json requires fedeisas/laravel-mail-css-inliner ^3.1 -> satisfiable by fedeisas/laravel-mail-css-inliner[3.1].     - fedeisas/laravel-mail-css-inliner 3.1 requires php ^7.2.5 -> your php version (8.0.5) does not satisfy that requirement.

### ISSUE THREAD

**Issue by roxshivamsingh** [fedeisas/laravel-mail-css-inliner#160]
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires fedeisas/laravel-mail-css-inliner ^3.1 -> satisfiable by fedeisas/laravel-mail-css-inliner[3.1].
    - fedeisas/laravel-mail-css-inliner 3.1 requires php ^7.2.5 -> your php version (8.0.5) does not satisfy that requirement.

**Comment by federicorp** [comment]
You could try to use the 4.0, that's the one that supports php 8.0.

**Comment by DannyvdSluijs** [comment]
@roxshivamsingh  In an attempt to cleanup this repository I'm looking at the open issues including yours.

It seems federicorp has provided you with an answer and I was curious if this resolved your issue, if so we can close the issue and have one less issue.

**Comment by DannyvdSluijs** [comment]
Closing based on the 👍🏼  emoji response on my previous comment by the reporter.
