### ISSUE TITLE
Using it outside emails

### ISSUE THREAD

**Issue by nam-co** [fedeisas/laravel-mail-css-inliner#162]
Hi, is there a way process the css inline apart from email? For example applied it to any blade file, like a facade?

**Comment by fedeisas** [comment]
I'd rather keep the most minimal functionality on this package.

You can take a look at https://github.com/fedeisas/laravel-mail-css-inliner/blob/6140c59192ad8d44fe0338a19a1e2cadaff1f8b9/src/CssInlinerPlugin.php#L98.
