### ISSUE TITLE
file_get_contents(): SSL operation failed with code 1

### ISSUE THREAD

**Issue by cerrito958** [fedeisas/laravel-mail-css-inliner#164]
Hi, Fedeisas.

   When I try to send mails in production with SSL, i get the error:
file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages: error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type

Stack Trace:
Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
vendor/fedeisas/laravel-mail-css-inliner/src/CssInlinerPlugin.php:90

Hope you can help me out?

**Comment by tohir87** [comment]
Also having the same problem here. Any help would be appreciated.

**Comment by cerrito958** [comment]
> También tengo el mismo problema aquí. Cualquier ayuda sería apreciada.

Hi, @tohir87, if you have you stylesheet asset in emal view, you need remove it, and add the .css in config/css-inliner.php, like this:

<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Css Files
    |--------------------------------------------------------------------------
    |
    | Css file of your style for your emails
    | The content of these files will be added directly into the inliner
    | Use absolute paths, ie. public_path('css/main.css')
    |
    */

    'css-files' => [
        public_path ('css/yourfileemail.css'),
    ],

];

Sorry for my english.
