### ISSUE TITLE
Only applies to default mailer

### ISSUE THREAD

**Issue by deevus** [fedeisas/laravel-mail-css-inliner#165]
This code only registers the plugin onto the default mailer. 

https://github.com/fedeisas/laravel-mail-css-inliner/blob/285036b484f0f7642150388f68f00f93798ac7cb/src/LaravelMailCssInlinerServiceProvider.php#L33-L36

We're using multiple mailers so it would be good if this package could support multiple mailers out of the box. 

At a glance it doesn't look like this can work with Laravel 7 at least. There doesn't appear to be any vector to register a plugin with a transport since only the default mailer is resolved using dependency injection out of the box. 

May just be worth adding some more information to the README if no other solution can be found.

**Comment by DannyvdSluijs** [comment]
@deevus In an attempt to cleanup this repository I'm looking at the open issues including yours.
It seems you're using additional mailers, which ones are these and are they supported by Laravel?

I would like to improve this library and was wondering if you inputs could usefully to put into the readme. Would you have some ideas on what it is we should add or maybe you could even open an pull request for this?

**Comment by DannyvdSluijs** [comment]
@deevus I'll close the issue for now. If you think this is incorrect and at any time want to revisit this issue feel free to open it.

**Comment by deevus** [comment]
Apologies for only getting back to this now. What I ended up doing was extending the `MailManager` class, injecting `CssInlinerPlugin`, and overriding the `createTransport` method. 

```php
class MailManager extends BaseMailManager
{
    protected CssInlinerPlugin $cssInlinerPlugin;

    public function __construct(
        Application $app,
        CssInlinerPlugin $cssInlinerPlugin
    ) {
        parent::__construct($app);

        $this->cssInlinerPlugin = $cssInlinerPlugin;
    }

    public function createTransport(array $config)
    {
        $transport = parent::createTransport($config);
        $transport->registerPlugin($this->cssInlinerPlugin);

        return $transport;
    }
}
```

I wish the Laravel developers would use DI more often. Hacks like this often have to be made to do things that should be easy.
