### ISSUE TITLE
Someday Laravel 9

### ISSUE THREAD

**Issue by nam-co** [fedeisas/laravel-mail-css-inliner#169]
Hi @fedeisas , good day, I was wondering, It seems Laravel is moving from SwiftMailer to Symfony Mailer in version 9, is this something that will be supported? thanks for everything

**Comment by jimleeder123** [comment]
Any updates on Laravel 9 support, please?

**Comment by ivanvermeyen** [comment]
Been tinkering with a temporary solution.
This is very basic can still be improved and maybe used in this package, since this package already offers extra feats.
I'm hooking into the `MessageSending` event and then convert the HTML.

```php
// app/Providers/EventServiceProvider.php

namespace App\Providers;

use App\ApplyInlineCssToMailBody;
use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;
use Illuminate\Mail\Events\MessageSending;

class EventServiceProvider extends ServiceProvider
{
    /**
     * The event listener mappings for the application.
     *
     * @var array
     */
    protected $listen = [
        MessageSending::class => [
            ApplyInlineCssToMailBody::class,
        ]
    ];

    /**
     * Register any events for your application.
     *
     * @return void
     */
    public function boot()
    {
        //
    }
}
```

```php
// app/ApplyInlineCssToMailBody.php

namespace App;

use Illuminate\Mail\Events\MessageSending;
use TijsVerkoyen\CssToInlineStyles\CssToInlineStyles;

class ApplyInlineCssToMailBody
{
    public function handle(MessageSending $event)
    {
        $html = (new CssToInlineStyles)->convert(
            $event->message->getHtmlBody(),
            file_get_contents(public_path('css/app.css'))
        );

        $event->message->html($html);
    }
}
```

**Comment by bintzandt** [comment]
Nice solution!

However, it does not work when the mail is send via an queue.

Does anybody have an idea how to get this working in a non-synchronous environment?

I looked at the [queue documentation](https://laravel.com/docs/9.x/queues) but I did not think Middleware was the way to go.

**Comment by ivanvermeyen** [comment]
@bintzandt are you sure it's not working with the queue?
I just ran this on my staging server using a redis queue, inspected the mail in mailtrap.io and CSS was inlined.

**Comment by stayallive** [comment]
@phanan I am currently not interested in that, I've made the fork a few years back to be able to use in my projects and change a few things to my liking. But feel free to take the changes from my fork and create a PR for this package it's all open source 😄 (but don't blindly copy since I've made some naming changes that would be a breaking change here)
