### ISSUE TITLE
CSS not inlined for mail with attachment

### ISSUE THREAD

**Issue by kverstae** [fedeisas/laravel-mail-css-inliner#175]
After updating to a laravel 9-compatible version of this package, I noticed that the CSS of mails with an attachment is not inlined any more.

I started looking in the code and noticed that `MixedPart` is just not handled here: https://github.com/fedeisas/laravel-mail-css-inliner/blob/6140c59192ad8d44fe0338a19a1e2cadaff1f8b9/src/CssInlinerPlugin.php#L86-L96
First intuition would be to handle `MixedPart` the same way as `AlternativePart`, which does work but has an unwanted side-effect: html attachments are also CSS inlined... This is not necessary and can potentially break the attached html file layout if the wrong CSS is inlined due to class-name collisions with the main mail content.

I am willing to create a PR for this, but would like some input first on how to handle this best in this project.

**Comment by ajohnson6494** [comment]
@kverstae Take a look at the PR #178 I just created and see if this solves your problem. Any feedback would be greatly appreciated.

**Comment by kverstae** [comment]
It now indeed correctly inlines the CSS for mails with an attachment, but still has a flaw: html attachments are also CSS inlined.
The issue is that `getParts()` also returns the attachments as parts and if this part has a mime type of 'text/html' it will be processed by `processPart()`, which should be avoided IMO.

**Comment by DannyvdSluijs** [comment]
@kverstae and @ajohnson6494  In an attempt to cleanup this repository I'm looking at the open issues including this one.
I was wondering if there is anything needed to put the progress on this back in motion?

**Comment by kverstae** [comment]
I created a PR #241 in an attempt to fix this. It seems to work for my usecase, but I am not 100% sure this will cover all edge cases. There might be some issues with more complex mail structures, but I am not sure if this can/will ever happen when using the Laravel mailing system.

**Comment by kverstae** [comment]
Do you mean the original class name? These are indeed still there and could maybe cause some issues if the mail client tries to interpret them with a css file it has somewhere (pure speculation, I have no idea how this works). This was also in the older versions of this package and didn't seem to cause any issues.

About the more complex mails. You could in theory build the mail from its raw Mime components in the Symfony framework (https://symfony.com/doc/current/components/mime.html#creating-raw-email-messages) and get some very unusual structures by doing so.
In the normal mail structure, the content is at the beginning of the mail body, followed by the attachment(s). This is also the assumption that is made here, so if this structure is different the attachment might get inlined css instead of the mail content...
Since this package is specific for Laravel, which adheres to the standard set by Symfony, this shouldn't be an issue but it is something that needs to be kept in mind.

**Comment by it-dubbelglas** [comment]
I rely on this package for beautiful email. Please merge fix ❤️

**Comment by wvanooijen92** [comment]
Sorry for the late response, just got back from vacation.

> Do you mean the original class name? 

And also the styling is in a style tag, this might not be a problem. Usually mail clients only checks inline styles, that's why I was surprised. I have not come across email clients that refuse to render the html because of it. To be honest, I think this package was doing it like this to begin with.

> Since this package is specific for Laravel, which adheres to the standard set by Symfony, this shouldn't be an issue but it is something that needs to be kept in mind.

I wonder if there is a reason for working with raw Mime components. And even if people are doing that shouldn't they use twig to do it's inline css magic? https://symfony.com/doc/current/components/mime.html#inlining-css-styles-and-other-extensions
