### ISSUE TITLE
Bootstrap styles not as expected

### ISSUE THREAD

**Issue by slavii** [fedeisas/laravel-mail-css-inliner#183]
Hello, 
I have read a lot about including styles in Laravel Mails and found this excellent package. 
After adding it I have made a lot of tests also with Gmail and Mailtrap, but the email style is not as expected. 

I have tried to add: 
- fonts.googleapis.css 
- bootstrap.min.css 
- custom css file (a few changes by me) 
- all.min.css (needed for font awesome icons) 
Font awesome icons should be at the bottom, but anyway, in both cases they do not show. 

The amount of the css content is large indeed but I am not sure this is the exact issue. 
Excuse me for the different language, but there are just two example screenshots from Gmail and Mailtrap. 

![gmail](https://user-images.githubusercontent.com/27051128/164313391-2de5be00-0613-4fc0-a7e3-a1f7d568afe6.png)
![mailtrap](https://user-images.githubusercontent.com/27051128/164313421-1c1397f5-f20d-4da8-b30a-3f415145a228.png)

It is quite possible that I did something wrong, but I could not find the right way. 

Thank you!

**Comment by DannyvdSluijs** [comment]
@slavii  In an attempt to cleanup this repository I'm looking at the open issues including yours.
It seems you've found an issue with this library. I was wondering if you looked at the raw email (HTML) contents and checked if you where able to have some idea of what goes wrong?

**Comment by slavii** [comment]
> @slavii In an attempt to cleanup this repository I'm looking at the open issues including yours. It seems you've found an issue with this library. I was wondering if you looked at the raw email (HTML) contents and checked if you where able to have some idea of what goes wrong?

Sorry for the delayed reply. 
I have already switch to another way for email styling.

**Comment by DannyvdSluijs** [comment]
Closing the issue for now then. Feel free to reopen it if needed.
