### ISSUE TITLE
Can you tag a new release?

### ISSUE THREAD

**Issue by ralphjsmit** [fedeisas/laravel-mail-css-inliner#192]
I had problems installing this with Laravel 9, because the `composer.json` of the latest tag doesn't allow `illuminate/mail: ^9.0`. Then I saw that this constraint _was_ already allowed on master. I currently installed it with the `dev-master` constraint, but I'd prefer to install this using a real tag. 

Therefore the question, can you tag a new release (like 4.1)? Thanks!

**Comment by emielmolenaar** [comment]
This would be nice

**Comment by alnorth** [comment]
It would be great if you could tag a release or, at least, give an indication that the code on `master` is ready for production use. This is currently blocking our upgrade to Laravel 9 because I'm reluctant to use `dev-master` in production.

**Comment by DannyvdSluijs** [comment]
I could also benefit from a new tag. It seems this repo has been quite inactive lately (no judgment, just as an observation).
But perhaps a ping for @fedeisas would help?

I believe that maintainers can also have a shift of mind, priorities change or a new job that doesn't allow for OSS work. But it would be in the benefit of the repo to make it clear if the package would be abandoned. Optionally even handed over to other maintainers. Anyway shoutout to Fede Isas for putting in all the earlier effort he has put in.

**Comment by ajohnson6494** [comment]
@DannyvdSluijs I have created a fork of this repo and have it updated to work with laravel 9 and symphony mailer if you are interested. I plan on maintaining this repo for a while as I currently use it on multiple production sites.

[Laravel Symfony Mailer CSS Inliner](https://github.com/ajohnson6494/laravel-symfony-mailer-css-inliner)

**Comment by lukebouch** [comment]
Can you please tag another release?

**Comment by fedeisas** [comment]
@DannyvdSluijs just made you a collaborator of this repo.

**Comment by fedeisas** [comment]
https://github.com/fedeisas/laravel-mail-css-inliner/releases/tag/5.0

**Comment by DannyvdSluijs** [comment]
> @DannyvdSluijs I just made you a collaborator on this repo.

Thanks, I'll accept for now and see how I can help and how it pans out. Anything you want to share with regards to this package or things you would like to to see resolved or addressed?
