### ISSUE TITLE
Optionally don't strip all tags

### ISSUE THREAD

**Issue by barryvdh** [fedeisas/laravel-mail-css-inliner#2]
Hey,

Just a heads up, using `setStripOriginalStyleTags` does save bytes, but it also removes media styles (and pseudo selectors). So for responsive newsletters, you probably don't want that. Maybe make it a config or something. (Or fix this issue https://github.com/tijsverkoyen/CssToInlineStyles/issues/45 ;))

**Comment by kibiz0r** [comment]
It would be nice to have a config for this. I need to strip the original style tags, so for the time being I'll be using a fork.

**Comment by EHLOVader** [comment]
This looks like it was fixed https://github.com/tijsverkoyen/CssToInlineStyles/pull/54 think it could be added again to resolve https://github.com/fedeisas/laravel-mail-css-inliner/issues/19

**Comment by sebdesign** [comment]
May I send a PR to add a config for this issue?
