### ISSUE TITLE
Load from external css files

### ISSUE THREAD

**Issue by Roywcm** [fedeisas/laravel-mail-css-inliner#21]
It would be great to load the css from an external <link> file so I don't have to (re)place all the css in the html after my less file compiled everything.

**Comment by Maidomax** [comment]
:+1:

**Comment by rafael-renan-pacheco** [comment]
You can use php function **file_get_contents()** like this:

https://github.com/Snowfire/Beautymail/blob/master/src/views/templates/ark.blade.php#L5

**Comment by jdavidbakr** [comment]
+1 - barryvdh\laravel-dompdf does this, would make it feel a bit more cohesive I think.  Not sure how easy it would be to implement, though.
