### ISSUE TITLE
Plugin not executing

### ISSUE THREAD

**Issue by jaesung2061** [fedeisas/laravel-mail-css-inliner#23]
The `Swift_Mailer` class is executing `registerPlugin($plugin)` with `$plugin` being `CssInlinerPlugin`. But it isn't executing `beforeSendPerformed()` before sending the mail. What could be the issue?
Please let me know what other information you might need.

I'm using Mandrill as the mail driver.

**Comment by ceesvanegmond** [comment]
@jaesung2061 Do you still have this problem?

**Comment by jaesung2061** [comment]
No. It turns out Laravel never made use of Swift plugins (they were never registered them). I made a pull request to fix it. https://github.com/laravel/framework/pull/9345
