### ISSUE TITLE
How to use this 

### ISSUE THREAD

**Issue by ajitbohra** [fedeisas/laravel-mail-css-inliner#24]
sorry for being naive how to use this any additional steps needed apart from adding provider ?

**Comment by ceesvanegmond** [comment]
@ajitbohra Do you still have problems with it? I think the README has enough information to get started.

**Comment by kingsloi** [comment]
@ceesvanegmond, if someone has to ask you how to use it, then it's probably not as clear as you might think

**Comment by ceesvanegmond** [comment]
@kingsloi Feel free to improve the docs!

**Comment by RomainSauvaire** [comment]
I should be naive too because even after running 
```composer require fedeisas/laravel-mail-css-inliner```

When I send (to the logs) an email which extends a layout, with `style` in it, it doesn't inline anything. Could use some of your advices.

### Example
```
@extends('layouts.email')

@section('content')
    <style>
        .test {
            font-size:3rem;
        }
        .test2 {
            font-weight: bold;
        }
        .test3 {
            color: red;
        }
    </style>
    <tr class="test">
        <td class="test2">
            <span class="test3">Pop</span>
        </td>
    </tr>
@endsection
```

**Comment by bcalik** [comment]
I installed as its instructed in readme, but it does not inline any css. Even a simple example doesn't work. I checked it using `log` mail driver. I tried this on a Laravel 5.2 project.
