### ISSUE TITLE
Laravel 9 issue

### ISSUE THREAD

**Issue by gilbertogm85** [fedeisas/laravel-mail-css-inliner#258]
After I updated our project to laravel 9 and updated the package as well, on the method
(https://github.com/fedeisas/laravel-mail-css-inliner/blob/6140c59192ad8d44fe0338a19a1e2cadaff1f8b9/src/CssInlinerPlugin.php#L86-L96)

Our `body` is instance of `RelatedPart` which extends AbstractPart as well as AlternativePart. So we had to override the method to:

`} elseif ($body instanceof AbstractPart) { `

Any chance of this being changed as they both extend AbstractPart? Or at least add an extra validation for RelatedPart objects?

`} elseif ($body instanceof AlternativePart || $body instanceof RelatedPart) { `

Thanks a lot!

**Comment by fedeisas** [comment]
@gilbertogm85 are you still seeing this using the latest version?

**Comment by gilbertogm85** [comment]
I stopped using and we are using `tijsverkoyen/css-to-inline-styles` at the moment. Is it fixed?

**Comment by DannyvdSluijs** [comment]
@gilbertogm85 the [question](https://github.com/fedeisas/laravel-mail-css-inliner/issues/258#issuecomment-1438737155) was actually at you
> are you still seeing this using the latest version?

We don't have any others reporting the same ATM. I'm good on continuing with this issue but I would need your inputs as well.

**Comment by DannyvdSluijs** [comment]
Closing this issue for now. @gilbertogm85 feel free to reopen en provide additional information in order to continue.
