### ISSUE TITLE
Needs a 1.4 release

### ISSUE THREAD

**Issue by mattstauffer** [fedeisas/laravel-mail-css-inliner#26]
Important changes have been made to the project with regard to dependencies that cannot be pulled into stable projects until there is a 1.4 tag.

**Comment by ceesvanegmond** [comment]
+1

**Comment by Souldat** [comment]
+1

**Comment by ceesvanegmond** [comment]
@mattstauffer @Souldat Tag created -> https://github.com/fedeisas/laravel-mail-css-inliner/releases/tag/1.4

**Comment by mattstauffer** [comment]
@ceesvanegmond <3 thank you!
