### ISSUE TITLE
Does not work with Symfony Postmark Mailer

### ISSUE THREAD

**Issue by deevus** [fedeisas/laravel-mail-css-inliner#261]
The Postmark Mailer calls `getTextBody()` and `getHtmlBody()` as shown here:

https://github.com/symfony/postmark-mailer/blob/5f38d688df43bea507bf0dfe0d0ca6f99221b708/Transport/PostmarkApiTransport.php#L89-L90

Under the hood those return return `$email->text` and `$email->html` which `CssInlinerPlugin` does not mutate when the `handleSymfonyMessage` method executes. It only mutates `$email->body`. 

https://github.com/fedeisas/laravel-mail-css-inliner/blob/f06926ac2882e716c02a7bc8da2cdcd642add60f/src/CssInlinerPlugin.php#L78-L96

It seems to be my impression that the `html` and `text` properties should also be updated?

**Comment by deevus** [comment]
Additionally when the `Mailer` class adds content to the message, it uses the `html()` and `text()` methods

https://github.com/laravel/framework/blob/31091a54085101f743960c9ca013058028e6ea35/src/Illuminate/Mail/Mailer.php#L355-L368

**Comment by deevus** [comment]
Fixed here 13e5f48d7c0711e79677d6e5d56ed74a7ed86039

If you would accept a PR, I can clean this up and open one

**Comment by OITDE** [comment]
Hi!

can you please add the PR? We have the same problem when using sendinblue as a mailservice.

Thanks!!

Regards, Ingo

**Comment by DannyvdSluijs** [comment]
Closing due to lack of response.
