### ISSUE TITLE
This would be cool... (removing <style> tag)

### ISSUE THREAD

**Issue by HeadStudios** [fedeisas/laravel-mail-css-inliner#275]
If you inline the styles removing the <style> tags after doing the inlining would be cool... like save a couple of KB maybe... or is that on the options if I do the second command? Thanks!

**Comment by DannyvdSluijs** [comment]
Hi @HeadStudios 

I missed you suggestion here. I think it would be a good size saver if you can remove all `<style></style>` (15 characters) I'm not sure if it would save kilobytes of data as that means you would need about 70 stylesheets linked before you can save a single kilobyte.

We are open to pull requests and I encourage you to create one.

**Comment by DannyvdSluijs** [comment]
Closing due to lack of response.
