### ISSUE TITLE
Anyway to dynamically assign what css files to include?

### ISSUE THREAD

**Issue by abishekrsrikaanth** [fedeisas/laravel-mail-css-inliner#309]
So, I am setting up css files based on theme colors and would like for a way to pass which css file to include when a mail is being sent, Is there a way to tell the package to only include `green.css` or `blue.css` to be inlined into the email?

**Comment by DannyvdSluijs** [comment]
Currently this library doesn’t offer such a feature. It does a complete inline of any css files where needed.

**Comment by DannyvdSluijs** [comment]
I guess my previous comment did leave this issue a bit dangling. Did the previous comment answer your questions or is there anything left to be answered?

**Comment by DannyvdSluijs** [comment]
Closing the issue for now due to no feedback. @abishekrsrikaanth  feel free to re-open the issue with additional details and we can take a look with some fresh eyes.
