### ISSUE TITLE
Can't publish the config file.

### ISSUE THREAD

**Issue by anchan42** [fedeisas/laravel-mail-css-inliner#312]
Running this `php artisan vendor: publish --provider='Fedeisas\LaravelMailCssInliner\LaravelMailCssInlinerServiceProvider'`
Return this error:    INFO  No publishable resources for tag [].
There is no config file showing up in the config directory. This is with Laravel 10.

**Comment by kirkbushell** [comment]
You've got a space between vendor: and publish.

**Comment by DannyvdSluijs** [comment]
@anchan42 did the comment from @kirkbushell help you?

I've recently created a [Laravel10MailCssInliner](https://github.com/DannyvdSluijs/Laravel10MailCssInliner) playground for which I've ran the same command without any issues.  I would be included to close the issue if no further details or reproduction steps can be shared.

**Comment by DannyvdSluijs** [comment]
Closing issue for now due to lack of feedback. Feel free to re-open with new information when needed.
