### ISSUE TITLE
Can I use this in Laravel 10 and Vite?

### ISSUE THREAD

**Issue by peppermint01** [fedeisas/laravel-mail-css-inliner#315]
Can this library be used as below?

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

    <!-- The CSS stylesheet which will be inlined. -->
    {{-- <link rel="stylesheet" type="text/css" href="{{ mix('css/mail.css') }}"> --}}
    @vite('resources/css/app.css')
</head>
<body>
    <div class="w-full h-full px-8 py-12">
        <p class="text-lg font-semibold text-purple-600">Test</p>
    </div>
</body>
</html>
```

    
    Thanks

**Comment by DannyvdSluijs** [comment]
@peprmint1 this issue report has lost my attention, I'm trying to see what it is your running into but the description of you issue seems to be lacking some details. Could you elaborate?

**Comment by danives** [comment]
I've encountered a similar issue with using Vite and Tailwind CSS, with a few "not great" solutions. I've made a repo so you can check out and run to see what might be being talked about: https://github.com/danives/mail-inline-test

**Comment by kirkbushell** [comment]
This is why: https://github.com/fedeisas/laravel-mail-css-inliner/issues/201

@DannyvdSluijs - same problem, I think - css inliner needs to not just assume that the file exists - it probably needs to provide a helper, so that when vite is running, it's doing a curl request to the file on the vite runtime.
