### ISSUE TITLE
Upgrade to tijsverkoyen/css-to-inline-styles ^2.0

### ISSUE THREAD

**Issue by GrahamCampbell** [fedeisas/laravel-mail-css-inliner#32]
This upgrade will take a bit more than just changing the version constraint I'm afraid, but it shouldn't be that bad to do.

**Comment by GrahamCampbell** [comment]
NB, this should need a new major release in this package too, for BC reasons.

**Comment by ceesvanegmond** [comment]
I totally agree. Right now I don't have the time to upgrade package. Feel free to open a pull request.

**Comment by Belphemur** [comment]
I've done this in #38 @ceesvanegmond & @GrahamCampbell 
The only test breaking is HHVM but it's due of the underlying lib itself then laravel-mail-css-inliner

Best addition is the possibility to set some CSS file to be used for the inlining rather that using <style />.

**Comment by ceesvanegmond** [comment]
@Belphemur Looks good!
