### ISSUE TITLE
Laravel v11

### ISSUE THREAD

**Issue by nam-co** [fedeisas/laravel-mail-css-inliner#322]
L11 its finally out

**Comment by rolfdenhartog** [comment]
See https://github.com/fedeisas/laravel-mail-css-inliner/pull/320

**Comment by nam-co** [comment]
@fedeisas Doc primero que todo gracias por el trabajo en mail-css-inliner, pero si ya no tienes tiempo porque no nombrar alguien que quiera administrarlo?

**Comment by ivalkenburg** [comment]
Could we get this merged? Much appreciated

**Comment by DannyvdSluijs** [comment]
#320 was merged, adding Laravel 11 support

**Comment by DannyvdSluijs** [comment]
Version 5.3.0 was released
- https://github.com/fedeisas/laravel-mail-css-inliner/releases/tag/5.3.0
- https://packagist.org/packages/fedeisas/laravel-mail-css-inliner#5.3.0
