### ISSUE TITLE
How can I use this package?

### ISSUE THREAD

**Issue by kamrava** [fedeisas/laravel-mail-css-inliner#34]
Hi,

I have installed this package on my Laravel project( v 5.2)
Now, how can I use this package?
Please show us an example of how can use this?!

Thanks,

**Comment by ikovbas** [comment]
Hi @kamrava 

You should install the package using the instruction from here https://github.com/fedeisas/laravel-mail-css-inliner#installation
And after that you should just send your mails via Laravel Mail facade https://laravel.com/docs/5.2/mail

Actually, I didn't work with this package on Laravel 5.2, but on Laravel 5.1 it works correctly for me.

**Comment by ceesvanegmond** [comment]
@kamrava Did you succeed to use the package? If improvements are needed on the docs, please do a pull request!
