### ISSUE TITLE
Call to undefined function Fedeisas\LaravelMailCssInliner\config_path()

### ISSUE THREAD

**Issue by njbarrett** [fedeisas/laravel-mail-css-inliner#35]
Installing this on a fresh Lumen 5.2 install I get this error.

`Call to undefined function Fedeisas\LaravelMailCssInliner\config_path()`

**Comment by njbarrett** [comment]
Seems that `config_path` is a missing function in Lumen, so following this I was able to fix it:

https://gist.github.com/mabasic/21d13eab12462e596120

**Comment by ceesvanegmond** [comment]
@njbarrett A really?!? That's something I need to fix. I will look into it later

**Comment by Pablodotnet** [comment]
Same is happening to me :( I'm using Lumen 5.1

**Comment by ceesvanegmond** [comment]
@njbarrett Could you make a pull request?

**Comment by njbarrett** [comment]
@ceesvanegmond PR opened
