### ISSUE TITLE
Not adding inline styles in 5.3

### ISSUE THREAD

**Issue by DelightedD0D** [fedeisas/laravel-mail-css-inliner#39]
Im using laravel 5.3. The inliner runs when I send mail and removes all but the media query css from the head but it does not add any inline styles whatsoever. Any ideas?

**Comment by ceesvanegmond** [comment]
Email isn't supporting inline media queries. http://stackoverflow.com/questions/9808233/is-it-possible-to-put-css-media-rules-inline
