### ISSUE TITLE
Laravel 5.4 compatibility

### ISSUE THREAD

**Issue by matomoravcik** [fedeisas/laravel-mail-css-inliner#44]
Hi i would like to ask if this is compatible with laravel 5.4 - it's not working for me on L 5.4. Thanks

**Comment by bryceadams** [comment]
+1 - broken with 2.1 update

**Comment by ceesvanegmond** [comment]
I will accept an pull request to be compatible with Laravel 5.4.

**Comment by Belphemur** [comment]
My pull #43 that has been merged should resolve this issue.

**Comment by matomoravcik** [comment]
@Belphemur yes this fix compatibility issue, thanks a lot
