### ISSUE TITLE
laravel 5.5 auto-discovery support

### ISSUE THREAD

**Issue by fideloper** [fedeisas/laravel-mail-css-inliner#45]
Hello!

I've had a simple PR on a project to support laravel 5.5 auto-discovery of service providers which I believe you should be able to replicate here.

(I haven't made a PR since I am not available to test this package with this change on laravel 5.5 yet, but figured it would be helpful to send you the basics on the update - really simple change, assuming 5.5 hasn't changed how mail works!)

https://github.com/fideloper/TrustedProxy/pull/78

**Comment by fedeisas** [comment]
Thanks @fideloper, I'll take a look.

**Comment by ceesvanegmond** [comment]
@fedeisas @fideloper It is already merged 👍
