### ISSUE TITLE
Stocked on Mail::to(...)->send|queue()

### ISSUE THREAD

**Issue by daison12006013** [fedeisas/laravel-mail-css-inliner#46]
PHP 7.1
Laravel 4.2
Library Version 2.1

When using above such as `Mail::to($email)->send()` nor `queue()` the queue stocked and never go thru in my supervisor (beanstalkd)

So I rolled back to 2.0 just to use the old one, I should probably change my version now to restrict using 2.0.* only.

**Comment by fedeisas** [comment]
@daison12006013 are you sure the problem in your queue was because this library? Can you provide more information? Thanks.

**Comment by jbonnett92** [comment]
Did you make sure that you changed the queue driver from sync to something of your choice? Sync essentially runs before a response is made.

**Comment by fedeisas** [comment]
Closed due to inactivity.
