### ISSUE TITLE
Configuration to fetch on a default folder ?

### ISSUE THREAD

**Issue by khalyomede** [fedeisas/laravel-mail-css-inliner#47]
If I set my route to my css file like `/css/app.min.css`, it thrown an error instead.

To fix it I had to hard code the correct route in my HTML file
```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>@yield('title') - test</title>
	<link rel="stylesheet" href="./public/css/app.min.css" />
</head>
<body>
	@include('navbar')
	@yield('content')
</body>
</html>
```

But now I cannot debug the front in my browser, because when I launch my website, it start from `/public`, so instead of browsing `http://localhost:8000/public` I can do `http://localhost:8000` using `php artisan serve`.

Is there a way to configurate the class to say it should fetch at a default folder ?

**Comment by fedeisas** [comment]
Hi @khalyomede! Laravel have some beautiful helpers for that. The best way to do it is:
```
<link rel="stylesheet" href="{{ asset('css/app.min.css') }}"/>
```
