### ISSUE TITLE
Error file_get_contents

### ISSUE THREAD

**Issue by fridzema** [fedeisas/laravel-mail-css-inliner#48]
Hello fedeisas, 

Really like your package, works great in my emails. Unfortunately when i try to do a composer update or php artisan optimize etc. i get the error file_get_contents(css/email.css): failed to open stream: No such file or directory/. 

I can ensure that the package itself works when sending mail.

Hope you can help me out?

**Comment by fedeisas** [comment]
Are you including your CSS using the `config` file?

**Comment by fridzema** [comment]
Thanks for your answer, it works perfectly now!

**Comment by zmonteca** [comment]
I don't really get the logic here...

If we're using a standard layout with a relative url in the link tag (css/emails.css), this plugin removes that tag from the layout and then tries to fetch the stylesheet with file_get_contents. But that's going to fail every day of the week.

So are we expected to use an alternative layout without any link tag defined and then rely on the css-files option in the configs?

It would seem to me, that it would be smarter to either create an option to map the relative url to the full url or just implicitly append the public_path() to the relative url.

Mapping could go something like this: 

`
'css-files' => [
    'css/emails.css' => public_path('css/emails.css'),
],
`
Replace line 100: 

`
$css_file = $link_tags->item(0)->getAttribute('href');

$options['css-files'][] = preg_match('/^\//', $css_file) ? $css_file : public_path($css_file);
`

Thoughts?

**Comment by zmonteca** [comment]
I don't really get the logic here...

If we're using a standard layout with a relative url in the link tag (css/emails.css), this plugin removes that tag from the layout and then tries to fetch the stylesheet with file_get_contents. But that's going to fail every day of the week.

So are we expected to use an alternative layout without any link tag defined and then rely on the css-files option in the configs?

It would seem to me, that it would be smarter to either create an option to map the relative url to the full url or just implicitly append the public_path() to the relative url.

Mapping could go something like this:

`
'css-files' => [ 'css/emails.css' => public_path('css/emails.css'), ],
`

Or Replace line 100:

`
$css_file = $link_tags->item(0)->getAttribute('href');
$options['css-files'][] = preg_match('/^//', $css_file) ? $css_file : public_path($css_file);
`

Thoughts?

**Comment by fedeisas** [comment]
@Belphemur added that feature on e763ee2

I'm not sure what was the use case he/she had in mind.

**Comment by Belphemur** [comment]
@fedeisas Wrong commiter and commit. The feature of reading the css tag was made by @underthecocotree https://github.com/fedeisas/laravel-mail-css-inliner/commit/6d2a98efcb82f4745303400f3abdf2cc23703068

I only updated the underlying library and silence the error of the xml/html parser.

For the records, I agree with @zmonteca. I could take the time to add a new configuration (to avoid conflict with the existing one and making all the user having to change it) that would let you map path to directory.

Like 

```php
['css-directory-map' => ['css' => public_path('css')]]
```

In fact, if you want @fedeisas I can make a pull request to add this feature.

**Comment by zmonteca** [comment]
I created a pull request for my proposed latter approach, which checks if the file has a public path or not and if not, creates the path using public_path(). 

This approach solves the issue myself and @Belphemur spoke of where any time a dir/file.css is used it is automatically supported and pushed inline.
