### ISSUE TITLE
@import not working

### ISSUE THREAD

**Issue by blanxii** [fedeisas/laravel-mail-css-inliner#54]
Hello guys,

I'm trying to import a font from google fonts in my css file, the problem is that I can't use @import / or link (link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet") all of them was translated to @font-face property and ofc there's no main item called font-face to be replaced.

I think could be a nice idea if this library let all the @ properties in the style-head element or you have any suggestions to deal with it?

If I add in the header-style it works but I need in my css to overwrite it.

Thanks!

**Comment by incraigulous** [comment]
I'm hitting this problem when trying to use web fonts as well.

```
 <link type="text/css"
              rel="stylesheet"
              href="//fast.fonts.net/cssapi/MY_KEY.css"/>
```

**Comment by fedeisas** [comment]
Closed due to inactivity.
