### ISSUE TITLE
Mail Not sending

### ISSUE THREAD

**Issue by awolad** [fedeisas/laravel-mail-css-inliner#56]
Email not sending from my Laravel 5.1 (LTS) app after installing this package. But before installing this plugin I was able to send email. But in an email the cases not loading.

What I did:
1. In my application I am rendering a view.
2. That view extended from a master template.
3. After view render I am sending the view as email.
4. And Finally the email not loading css.

**Comment by fedeisas** [comment]
Closed due to inactivity.
