### ISSUE TITLE
outlook issues

### ISSUE THREAD

**Issue by nam-co** [fedeisas/laravel-mail-css-inliner#58]
Hi, first I would like to thank you for the package, is very helpful

Im having a problem with outlook where the fonts and button paddings are not showing, do you have any idea why or any recommendation?

here is the example of a html button

<--a href="#"  class="btn btn-primary bg-gray_light btn-round mt-0 font s-16" style="box-sizing: border-box; text-decoration: none; -webkit-text-decoration-skip: objects; display: inline-block; font-weight: 400; text-align: center; white-space: nowrap; vertical-align: middle; user-select: none; line-height: 1.5; transition: color 0.15s ease-in-out,background-color 0.15s ease-in-out,border-color 0.15s ease-in-out,box-shadow 0.15s ease-in-out; color: #fff; background-color: #4D6ED8; border-color: #4D6ED8; font-family: 'Source Sans Pro','Segoe UI','Helvetica Neue',Arial,sans-serif !important; cursor: pointer !important; -webkit-border-radius: 50px !important; -moz-border-radius: 50px !important; -ms-border-radius: 50px !important; border-radius: 50px !important; padding: 8px !important; padding-left: 24px !important; padding-right: 24px !important; border: none !important; outline: 0 !important; font-size: 16px !important; margin-top: 0px !important;">Something</a>

Appreciate any help
thanks

**Comment by fedeisas** [comment]
Closed due to inactivity.
