### ISSUE TITLE
Does not work when creating a new SmtpTransport

### ISSUE THREAD

**Issue by azzic** [fedeisas/laravel-mail-css-inliner#59]
Hi, 

Not sure if this is an issue or more of a question. 

Was wondering how could I attach your plugin to a dynamically created "new SmtpTransport (mail.host, 25, tls)".

It works great whenever I start the application and the default configuration used in the .env file, but whenever I try to create a "new SmtpTransport()" to update my mail server config, the plugin does not get attached into the #eventDispatcher, listeners[] of the smtpTransport. 

Thanks,

**Comment by echo909** [comment]
I had the same problem.

Try adding this to the new instance.

      ```
  $inlinerPlugin = $app->make(\Fedeisas\LaravelMailCssInliner\CssInlinerPlugin::class);
        $mailer->registerPlugin($inlinerPlugin);
```

**Comment by fedeisas** [comment]
Closed due to inactivity.
