### ISSUE TITLE
Media query

### ISSUE THREAD

**Issue by piep14** [fedeisas/laravel-mail-css-inliner#62]
Hello,

Why this code on responsive mobile don't work ? 

```
.picture-feed {
    width: 50%;
}

@media (max-width: 768px) {
    .picture-feed {
        width: 100%;
    }
}
```

My image is still 50%

Thank you for help.

**Comment by piep14** [comment]
Nobody ?

**Comment by thomasjohnkane** [comment]
Having the same issue with TailwindCSS. Everything is in the mobile view regardless.

**Comment by fedeisas** [comment]
@piep14 @thomasjohnkane I think the problem is that the plugin inlines your CSS and that takes precedence over your media queries. I'm not sure if you can expect TailwindCSS to work on an email client. There are frameworks that target those clients specifically.
