### ISSUE TITLE
Timeout - Bug report v2.2

### ISSUE THREAD

**Issue by manegame** [fedeisas/laravel-mail-css-inliner#64]
Hey everyone. Just ran into an issue with my Laravel build today and wanted to share the problem with the community.

My problem was with this line, which caused my mail jobs to timeout after 60 seconds:

<img width="662" alt="Schermafbeelding 2019-08-08 om 13 57 00" src="https://user-images.githubusercontent.com/17074938/62705561-ead92d80-b9ed-11e9-884e-c391acbf69ab.png">

It's happened to me on three different servers.

Laravel Framework 5.7.28

PHp Local: 
PHP 7.2.9 (cli) (built: Aug 21 2018 07:42:00) ( NTS )

PHP Server 1:
PHP 7.3.7-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jul 10 2019 06:54:26) ( NTS )

PHP Server 2:
PHP 7.2.20-2+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jul 25 2019 11:42:36) ( NTS )

Downgrading to 2.1 worked. I was using the dev branch. Does that mean it can be expected to fail?

Thanks for working on this amazing package!

**Comment by nrhooks1792** [comment]
I'm currently having this issue as well. The app times out when the 'rel' attribute is not present. Any update on this? Thank you!

**Comment by fedeisas** [comment]
@manegame @nrhooks1792 this fixed in the next release. Thanks.
