### ISSUE TITLE
Dont use Laravel 6.0

### ISSUE THREAD

**Issue by uiuifree** [fedeisas/laravel-mail-css-inliner#66]
I can't install with Laravel 6.0, so please update.

**Comment by stayallive** [comment]
There is already a PR pending #65, let's have some patience 😄

**Comment by seyfer** [comment]
do I understand correctly, that I need to use v2.3 tag for Laravel 6?
this one? https://github.com/fedeisas/laravel-mail-css-inliner/tree/2.3

**Comment by stayallive** [comment]
Yes, 2.3 is the last version supporting Laravel `6.x`.
