### ISSUE TITLE
Working with Mailgun

### ISSUE THREAD

**Issue by AntoineAugusti** [fedeisas/laravel-mail-css-inliner#7]
Hi!

I'm using Laravel 4.2.1 and the CSS doesn't get inlined when using Mailgun. Since 4.2 Mailgun is an email provider in Laravel.

I think that the send event is not caught when calling the Mailgun API. This is tricky because the email is not sent using Swift Mailer. A good idea would be to listen to  the `mailer.sending` event but it is currently throw just with swift messages and not with other transporters. Source: https://github.com/laravel/framework/blob/master/src/Illuminate/Mail/Mailer.php#L323

**Comment by dmyers** [comment]
Is there any way to fix the package to handle this, or do we need to wait until Laravel 5?

**Comment by ceesvanegmond** [comment]
@AntoineAugusti Do you still have this problem? Or is it resolved already?
