### ISSUE TITLE
Laravel 7 compatibility

### ISSUE THREAD

**Issue by vesper8** [fedeisas/laravel-mail-css-inliner#71]
`2.3` is not compatible with Laravel 7 due to `illuminate/support ~5.0|^6.0`

@fedeisas Could you please release a new version with Laravel 7 compatibility?

Thanks a lot!

**Comment by zupolgec** [comment]
See #72

**Comment by fedeisas** [comment]
@vesper8 @zupolgec tagging a new release tonight with Laravel 7 support. Thanks.
