### ISSUE TITLE
Mandrill-driver together with css-inliner

### ISSUE THREAD

**Issue by juukie** [fedeisas/laravel-mail-css-inliner#84]
Hi! First of all thanks for creating and maintaining this package :-).

I've installed it together with `therobfonz/laravel-mandrill-driver`. Both packages use Laravel's auto-discovery feature.

The css-inliner package boots before the mandrill-driver package, but since the css-inliner needs the SwiftMailer it tries to build the mail (Mandrill) transport which is not registered in the mail manager yet.

![Schermafbeelding 2020-04-30 om 16 04 21](https://user-images.githubusercontent.com/2678657/80722005-3218c880-8aff-11ea-966e-2e09e25f2ea9.png)

```
$this->app->extend('mail.manager', function (MailManager $mailManager) {
    $mailManager->getSwiftMailer()->registerPlugin($this->app->make(CssInlinerPlugin::class));
    return $mailManager;
});
``` 

To make both packages work I tried to add them to composer.json's `dont-discover` array:
```
"dont-discover": [
    "fedeisas/laravel-mail-css-inliner",
    "therobfonz/laravel-mandrill-driver" 
]
```
and register their service providers manually via `config/app.php`:
```
/** Package Service Providers... */
\LaravelMandrill\MandrillServiceProvider::class,
\Fedeisas\LaravelMailCssInliner\LaravelMailCssInlinerServiceProvider::class,
```
but it did not solve the problem straight away. Only when I moved
```
$this->app->extend('mail.manager', function (MailManager $mailManager) {
    $mailManager->getSwiftMailer()->registerPlugin($this->app->make(CssInlinerPlugin::class));
    return $mailManager;
});
``` 
into `LaravelMailCssInlinerServiceProvider::boot()`.

Since I shouldn't change the files in `/vendor`, I've added
```
$this->app->register(\Fedeisas\LaravelMailCssInliner\LaravelMailCssInlinerServiceProvider::class);
```
to `AppServiceProvider::boot()`.
So the `LaravelMailCssInlinerServiceProvider` will be registered after the laravel-mandrill-driver.

Both packages used to work together in Laravel 6. Laravel 7's changes on the mailing system seems to be the problem. Not sure if the solution to this issue would be to just move the extending of the mail.manager into boot() since `therobfonz/laravel-mandrill-driver` is auto-discovered after `fedeisas/laravel-mail-css-inliner`.

**Comment by lbeauvisage** [comment]
i Have the same problem with vemcogroup/laravel-sparkpost-driver

with this error 
```php
InvalidArgumentException
Unsupported mail transport [sparkpost].
```

<img width="1278" alt="Unsupported mail transport [sparkpost]." src="https://user-images.githubusercontent.com/786319/86365167-72b8cd80-bc79-11ea-9316-5052cda63ff2.png">

**Comment by Gimcrack** [comment]
I had the same issue with the sparkpost driver but was able to work around it by not auto-discovering `laravel-mail-css-inliner`.

```
// composer.json
...
"extra": {
  "laravel": {
    "dont-discover": [
      "fedeisas/laravel-mail-css-inliner"
    ]
  }
},
```

```
// app.config
...
'providers' => [
  ...
  Fedeisas\LaravelMailCssInliner\LaravelMailCssInlinerServiceProvider::class,
  ...
]
``

**Comment by fedeisas** [comment]
#90 should fix this.
