### ISSUE TITLE
Error when publishing config file

### ISSUE THREAD

**Issue by iplat64** [fedeisas/laravel-mail-css-inliner#98]
Hi there! Thanks for this very useful package.
After installing the package with composer, running the vendor:publish artisan command returns an error message "Unable to locate publishable resources". After manually copying the css-inliner.php file from the vendor folder to the config folder, everything works fine though.

**Comment by angelofan** [comment]
The same issue, I am using laravel 8

**Comment by treb00** [comment]
try without the quote

`php artisan vendor:publish --provider=Fedeisas\LaravelMailCssInliner\LaravelMailCssInlinerServiceProvider`
